version: '3.5'

services:
   database:
      container_name: template_database
      image: mongo:latest
      ports:
         - 27017:27017
      expose:
         - 27017
   server:
      build: packages/server
      container_name: template_server
      depends_on:
         - database
      ports:
         - 8080:8080
   web:
      build: packages/web
      container_name: template_web
      ports:
         - 5000:5000
