version: "3.3"

services:
    database:
        container_name: mongodb
        image: mongo
        environment:
            - MONGO_INITDB_DATABASE=test
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=secret
        ports:
            - 27017-27017
        volumes:
            - data:/data/db
volumes:
    data:
