version: "3.3"

services:
    mongodb:
        container_name: mongodb
        image: mongo
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=secret
        ports:
            - 27017-27017
        expose:
            - 27017
        volumes:
            - ./mongodb_data:/data/db
